# (로컬에서 시크릿 없이 실행할 때 생기는 에러 발생 해결 방법 중 하나.)
# 1. 사전에 이미지를 개인 계정에 업로드. (tag, push)
# 2. secret 생성. (쿠버네티스 입문 11.2.3 방법) 
#   kubectl create secret docker-registry dockersecret3 --docker-username=wwaust --docker-password=<password> --docker-email=changwooha89@gmail.com
# 3. 생성한 secret 이름을 imagePullSecrets.name에 입력
# 4. apply yaml

apiVersion: v1
kind: Service
metadata: 
  name: tf2-serve
spec: 
  type: LoadBalancer
  selector:
    app: tf2-serve
  ports: 
    - protocol: TCP
      port: 3200
      targetPort: 3000
      nodePort: 30010
